//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class dbFashionShoesEntities : DbContext
    {
        public dbFashionShoesEntities()
            : base("name=dbFashionShoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tb_ChucVu> tb_ChucVu { get; set; }
        public DbSet<tb_CTHDBanHang> tb_CTHDBanHang { get; set; }
        public DbSet<tb_CTPhieuDoiHang> tb_CTPhieuDoiHang { get; set; }
        public DbSet<tb_CTPhieuNhapHang> tb_CTPhieuNhapHang { get; set; }
        public DbSet<tb_CTPhieuTraHang> tb_CTPhieuTraHang { get; set; }
        public DbSet<tb_CuaHang> tb_CuaHang { get; set; }
        public DbSet<tb_DanhGia> tb_DanhGia { get; set; }
        public DbSet<tb_DanhMuc> tb_DanhMuc { get; set; }
        public DbSet<tb_HDBanHang> tb_HDBanHang { get; set; }
        public DbSet<tb_HeThongCuaHang> tb_HeThongCuaHang { get; set; }
        public DbSet<tb_KhachHang> tb_KhachHang { get; set; }
        public DbSet<tb_KhuyenMai> tb_KhuyenMai { get; set; }
        public DbSet<tb_MauSac> tb_MauSac { get; set; }
        public DbSet<tb_NCC_ThgHieu> tb_NCC_ThgHieu { get; set; }
        public DbSet<tb_NhaCungCap> tb_NhaCungCap { get; set; }
        public DbSet<tb_NhanVien> tb_NhanVien { get; set; }
        public DbSet<tb_PhieuDoiHang> tb_PhieuDoiHang { get; set; }
        public DbSet<tb_PhieuNhapHang> tb_PhieuNhapHang { get; set; }
        public DbSet<tb_PhieuTraHang> tb_PhieuTraHang { get; set; }
        public DbSet<tb_SanPham> tb_SanPham { get; set; }
        public DbSet<tb_Size> tb_Size { get; set; }
        public DbSet<tb_ThuongHieu> tb_ThuongHieu { get; set; }
        public DbSet<tb_TrangThaiHoaDon> tb_TrangThaiHoaDon { get; set; }
        public DbSet<tb_TrangThaiSanPham> tb_TrangThaiSanPham { get; set; }
    
        [DbFunction("dbFashionShoesEntities", "ChiTietDonHang")]
        public virtual IQueryable<ChiTietDonHang_Result> ChiTietDonHang(Nullable<int> maHDBH)
        {
            var maHDBHParameter = maHDBH.HasValue ?
                new ObjectParameter("MaHDBH", maHDBH) :
                new ObjectParameter("MaHDBH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ChiTietDonHang_Result>("[dbFashionShoesEntities].[ChiTietDonHang](@MaHDBH)", maHDBHParameter);
        }
    
        [DbFunction("dbFashionShoesEntities", "SanPham")]
        public virtual IQueryable<SanPham_Result> SanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SanPham_Result>("[dbFashionShoesEntities].[SanPham]()");
        }
    
        [DbFunction("dbFashionShoesEntities", "TimKiemSanPham")]
        public virtual IQueryable<TimKiemSanPham_Result> TimKiemSanPham(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("query", query) :
                new ObjectParameter("query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TimKiemSanPham_Result>("[dbFashionShoesEntities].[TimKiemSanPham](@query)", queryParameter);
        }
    
        [DbFunction("dbFashionShoesEntities", "top10SP")]
        public virtual IQueryable<top10SP_Result> top10SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<top10SP_Result>("[dbFashionShoesEntities].[top10SP]()");
        }
    
        public virtual ObjectResult<DonHang_Result> DonHang(string sDT)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DonHang_Result>("DonHang", sDTParameter);
        }
    
        public virtual int DuyetDonHang(Nullable<int> id, Nullable<int> maNV)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DuyetDonHang", idParameter, maNVParameter);
        }
    
        public virtual ObjectResult<LayTatCaDonHang_Result> LayTatCaDonHang(Nullable<int> id_trangthai)
        {
            var id_trangthaiParameter = id_trangthai.HasValue ?
                new ObjectParameter("id_trangthai", id_trangthai) :
                new ObjectParameter("id_trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayTatCaDonHang_Result>("LayTatCaDonHang", id_trangthaiParameter);
        }
    
        public virtual ObjectResult<LoginFashionShoes_Result> LoginFashionShoes(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginFashionShoes_Result>("LoginFashionShoes", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<ThongKeDoanhThu_Result> ThongKeDoanhThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeDoanhThu_Result>("ThongKeDoanhThu");
        }
    
        public virtual ObjectResult<ThongKeKhachHang_Result> ThongKeKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeKhachHang_Result>("ThongKeKhachHang");
        }
    
        public virtual ObjectResult<ThongKeNhanVien_Result> ThongKeNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeNhanVien_Result>("ThongKeNhanVien");
        }
    
        public virtual ObjectResult<ThongKeNhanVienDonHang_Result> ThongKeNhanVienDonHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeNhanVienDonHang_Result>("ThongKeNhanVienDonHang");
        }
    
        public virtual ObjectResult<ThongKeThuongHieuSaPham_Result> ThongKeThuongHieuSaPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeThuongHieuSaPham_Result>("ThongKeThuongHieuSaPham");
        }
    
        public virtual ObjectResult<ThongKeTop10SanPham_Result> ThongKeTop10SanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTop10SanPham_Result>("ThongKeTop10SanPham");
        }
    
        public virtual ObjectResult<TimKiemDonHang_Result> TimKiemDonHang(string sDT)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemDonHang_Result>("TimKiemDonHang", sDTParameter);
        }
    }
}
