//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CuaHang
    {
        public tb_CuaHang()
        {
            this.tb_CTHDBanHang = new HashSet<tb_CTHDBanHang>();
            this.tb_NhanVien = new HashSet<tb_NhanVien>();
        }
    
        public int MaCuaHang { get; set; }
        public int MaHeThong { get; set; }
        public string TenCuaHang { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<double> ToaDoX { get; set; }
        public Nullable<double> ToaDoY { get; set; }
    
        public virtual ICollection<tb_CTHDBanHang> tb_CTHDBanHang { get; set; }
        public virtual tb_HeThongCuaHang tb_HeThongCuaHang { get; set; }
        public virtual ICollection<tb_NhanVien> tb_NhanVien { get; set; }
    }
}
