//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTPhieuDoiHang
    {
        public int MaCTPhieuDoiHang { get; set; }
        public int MaPhieuDoiHang { get; set; }
        public int MaSP { get; set; }
        public int SL { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual tb_PhieuDoiHang tb_PhieuDoiHang { get; set; }
    }
}
