//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DanhGia
    {
        public int IDSP { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> DanhGia { get; set; }
    
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_SanPham tb_SanPham { get; set; }
    }
}
