//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HeThongCuaHang
    {
        public tb_HeThongCuaHang()
        {
            this.tb_CuaHang = new HashSet<tb_CuaHang>();
        }
    
        public int MaHeThong { get; set; }
        public Nullable<int> SLCuaHang { get; set; }
    
        public virtual ICollection<tb_CuaHang> tb_CuaHang { get; set; }
    }
}
