//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KhachHang
    {
        public tb_KhachHang()
        {
            this.tb_DanhGia = new HashSet<tb_DanhGia>();
            this.tb_HDBanHang = new HashSet<tb_HDBanHang>();
            this.tb_PhieuDoiHang = new HashSet<tb_PhieuDoiHang>();
        }
    
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<tb_DanhGia> tb_DanhGia { get; set; }
        public virtual ICollection<tb_HDBanHang> tb_HDBanHang { get; set; }
        public virtual ICollection<tb_PhieuDoiHang> tb_PhieuDoiHang { get; set; }
    }
}
