//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KhuyenMai
    {
        public tb_KhuyenMai()
        {
            this.tb_SanPham = new HashSet<tb_SanPham>();
        }
    
        public int MaKhuyenMai { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<double> PhanTram { get; set; }
    
        public virtual ICollection<tb_SanPham> tb_SanPham { get; set; }
    }
}
