//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhanVien
    {
        public tb_NhanVien()
        {
            this.tb_HDBanHang = new HashSet<tb_HDBanHang>();
            this.tb_PhieuDoiHang = new HashSet<tb_PhieuDoiHang>();
            this.tb_PhieuNhapHang = new HashSet<tb_PhieuNhapHang>();
            this.tb_PhieuTraHang = new HashSet<tb_PhieuTraHang>();
        }
    
        public int MaNV { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string Username { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public string Password { get; set; }
        public Nullable<int> ChucVu { get; set; }
        public int MaCuaHang { get; set; }
    
        public virtual tb_ChucVu tb_ChucVu { get; set; }
        public virtual tb_CuaHang tb_CuaHang { get; set; }
        public virtual ICollection<tb_HDBanHang> tb_HDBanHang { get; set; }
        public virtual ICollection<tb_PhieuDoiHang> tb_PhieuDoiHang { get; set; }
        public virtual ICollection<tb_PhieuNhapHang> tb_PhieuNhapHang { get; set; }
        public virtual ICollection<tb_PhieuTraHang> tb_PhieuTraHang { get; set; }
    }
}
