//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhaCungCap
    {
        public tb_NhaCungCap()
        {
            this.tb_NCC_ThgHieu = new HashSet<tb_NCC_ThgHieu>();
        }
    
        public int MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        public virtual ICollection<tb_NCC_ThgHieu> tb_NCC_ThgHieu { get; set; }
    }
}
