//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhieuTraHang
    {
        public tb_PhieuTraHang()
        {
            this.tb_CTPhieuTraHang = new HashSet<tb_CTPhieuTraHang>();
        }
    
        public int MaPhieuTraHang { get; set; }
        public Nullable<int> SLHang { get; set; }
        public int MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
    
        public virtual ICollection<tb_CTPhieuTraHang> tb_CTPhieuTraHang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
