//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhieuNhapHang
    {
        public tb_PhieuNhapHang()
        {
            this.tb_CTPhieuNhapHang = new HashSet<tb_CTPhieuNhapHang>();
        }
    
        public int MaHDNH { get; set; }
        public int MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public System.DateTime NgayDuyet { get; set; }
    
        public virtual ICollection<tb_CTPhieuNhapHang> tb_CTPhieuNhapHang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
