//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhieuDoiHang
    {
        public tb_PhieuDoiHang()
        {
            this.tb_CTPhieuDoiHang = new HashSet<tb_CTPhieuDoiHang>();
        }
    
        public int MaPhieuDoiHang { get; set; }
        public Nullable<int> SLHang { get; set; }
        public int MaNV { get; set; }
        public Nullable<int> MaKH { get; set; }
        public System.DateTime NgayLap { get; set; }
        public System.DateTime NgayDuyet { get; set; }
    
        public virtual ICollection<tb_CTPhieuDoiHang> tb_CTPhieuDoiHang { get; set; }
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
