//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tb_SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SanPham()
        {
            this.tb_CTHDBanHang = new HashSet<tb_CTHDBanHang>();
            this.tb_CTPhieuNhapHang = new HashSet<tb_CTPhieuNhapHang>();
            this.tb_DanhGia = new HashSet<tb_DanhGia>();
            this.tb_MauSac = new HashSet<tb_MauSac>();
            this.tb_Size = new HashSet<tb_Size>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        public string TenSP { get; set; }

        [Required(ErrorMessage = "Tên thương hiệu không được để trống")]
        public int ThgHieu { get; set; }

        [Required(ErrorMessage = "Danh mục không được để trống")]
        public int MaDanhMuc { get; set; }
        public int MaKhuyenMai { get; set; }

        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        public Nullable<decimal> GiaBan { get; set; }

        [Required(ErrorMessage = "Số lượng không được để trống")]
        public Nullable<int> SoLuongTon { get; set; }

        [Required(ErrorMessage = "Thời gian bảo hành không được để trống")]
        public int ThoiGianBH { get; set; }
        public string UrlHinh { get; set; }

        [Required(ErrorMessage = "Mô tả không được để trống")]
        [AllowHtml]
        public string MoTa { get; set; }

        public Nullable<int> TrangThai { get; set; }

        [Required(ErrorMessage = "Thông tin sản phẩm không được để trống")]
        [AllowHtml]
        public string ThongTinSP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDBanHang> tb_CTHDBanHang { get; set; }

         [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTPhieuNhapHang> tb_CTPhieuNhapHang { get; set; }
        public virtual ICollection<tb_DanhGia> tb_DanhGia { get; set; }
        public virtual tb_DanhMuc tb_DanhMuc { get; set; }
        public virtual tb_KhuyenMai tb_KhuyenMai { get; set; }
        public virtual tb_ThuongHieu tb_ThuongHieu { get; set; }
        public virtual tb_TrangThaiSanPham tb_TrangThaiSanPham { get; set; }
        public virtual ICollection<tb_MauSac> tb_MauSac { get; set; }
        public virtual ICollection<tb_Size> tb_Size { get; set; }
    }
}
