//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Size
    {
        public tb_Size()
        {
            this.tb_SanPham = new HashSet<tb_SanPham>();
        }
    
        public int MaSize { get; set; }
        public string TenSize { get; set; }
    
        public virtual ICollection<tb_SanPham> tb_SanPham { get; set; }
    }
}
