//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThuongHieu
    {
        public tb_ThuongHieu()
        {
            this.tb_NCC_ThgHieu = new HashSet<tb_NCC_ThgHieu>();
            this.tb_SanPham = new HashSet<tb_SanPham>();
        }
    
        public int MaThgHieu { get; set; }
        public string TenThgHieu { get; set; }
        public Nullable<bool> DaXoa { get; set; }
    
        public virtual ICollection<tb_NCC_ThgHieu> tb_NCC_ThgHieu { get; set; }
        public virtual ICollection<tb_SanPham> tb_SanPham { get; set; }
    }
}
