//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionShoes.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TrangThaiHoaDon
    {
        public tb_TrangThaiHoaDon()
        {
            this.tb_HDBanHang = new HashSet<tb_HDBanHang>();
        }
    
        public int ID { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<tb_HDBanHang> tb_HDBanHang { get; set; }
    }
}
